# Generated by Django 5.1.2 on 2024-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('periodo_experiencia', models.CharField(max_length=50)),
                ('descricao_atividades', models.TextField()),
                ('instituicao', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('periodo_formacao', models.CharField(max_length=50)),
            ],
        ),
    ]
